### PR TITLE
Keep original buffer

### PR DESCRIPTION
**Pull request by metsma**
IB-5311

Signed-off-by: Raul Metsma <raul@metsma.ee>

### CODE REVIEW

**Comment by glensc** [comment]
side effect of this PR is that now it compiles with Qt 5.11, otherwise would need this patch to compile the latest release:

- https://github.com/pld-linux/qesteidutil/commit/417a77a8594a413ffd3f30b5fdfeea072260d72c

**Comment by metsma** [comment]
Can you create separate pull request?

**Comment by glensc** [comment]
There's nothing to create. the changes to fix building with Qt 5.11 are in this PR.

**Comment by metsma** [comment]
I cannot merge already merged pull request

**Comment by glensc** [comment]
why do you want to merge anything? i was just [stating](https://github.com/open-eid/qesteidutil/pull/103#issuecomment-414988925) that this PR also fixed compile error for Qt 5.11.

if you want to do something, then you can make new release from `master`.

**Comment by metsma** [comment]
oh my bad, sorry

**Pull request merged**
